### PR TITLE
Use Doctrine Paginator instead of PaginationWalker in README examples

### LINKED ISSUE #6: Use Doctrine Paginator instead of PaginationWalker
Doctrine has had a [`Paginator` component](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/tutorials/pagination.html) ever since 2.2. I think it would make sense to use it instead of relying on your own MySQL-specific `PaginationWalker`. I found that in certain cases, `Paginator` even counts the results more correctly. In particular, `PaginationWalker` counted the results wrongly for me when I was filtering by properties of `OneToMany` relationships.

The code change is rather simple, you just replace the following lines in your repository class:
```php
$query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, PaginationWalker::class);
$query->setHint("mysqlWalker.sqlCalcFoundRows", true);
$result = $query->getResult();
$totalRows = $this->_em->getConnection()->query('SELECT FOUND_ROWS()')->fetchColumn();

// return the wrapped result
return new QueryResult($result, $totalRows);
```
with these:
```php
$paginator = new Paginator($query);

return new QueryResult($paginator->getIterator()->getArrayCopy(), count($paginator));
```

I could prepare a PR for that if you're interested. Perhaps it would even make sense to return the `Paginator` itself instead of wrapping its result in `QueryResult` and, subsequently, in `Response` (although that would mean an API change)?

On a separate note, I think it would be great if instead of (or in addition to) getting the `Response` (or `Paginator`) object with only the selected entities and the total count, I could get a `QueryBuilder` with the required filters, offset and limit already appied. This would allow me add extra fine-tuned constraints or perform other actions on the object. Basically, what I want is a library which would parse the query and apply filters to QueryBuilder as opposed to one that does everything from parsing to returning a results object. After seeing how simple to use `Paginator` is, it doesn't seem like instantiating it from outside controller provides any added value. If you agree, I can turn this comment into a separate issue.

### PR DESCRIPTION
**Pull request by rimas-kudelis**
Fixes #6 (except the lack of ability to get a `QueryBuider` object with all filters applied).

### CODE REVIEW

**Comment by denisvmedia** [comment]
Thank you for your efforts. The only issue however remained: one test is now broken ;)

**Comment by denisvmedia** [comment]
Hm... interesting, you changed only README, but the tests had failed. Will check it.

**Comment by denisvmedia** [comment]
Ok, I fixed the tests. Thank you for your efforts. Merging.

**Comment by rimas-kudelis** [comment]
Hehe. Yeah, stuff just happens with tests. :)

**Pull request merged**
